import Link from 'next/link';
import { Inter } from 'next/font/google'
import NavBar from './components/NavBar'
import Footer from './components/Footer'
import LinkBar from './components/LinkBar';


import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Omnex Group',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  
  return (
    <>
     <body className='flex flex-col min-h-screen'>
      <header className={inter.className}>
         <NavBar />
      </header>
      <main className='grow px-5'>
        {children}
      </main>
      <footer>
        <Footer/>
      </footer>
     </body>
    </>
  );
}