import Link from 'next/link';
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './components/NavBar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Omnex Group',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
     <body className='px-4'>
      <header className={inter.className}>
         <NavBar />
      </header>
      <main>
        {children}
      </main>
      <footer>
        <Footer/>
      </footer>
     </body>
    </>
  );
}