import Link from 'next/link';
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
     <header className={inter.className}>
        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <div className="dropdown">
                <button className="dropbtn">About Us</button>
                <ul className="dropdown-content">
                  <li><Link href="/about-us/corporate-press">Corporate Press</Link></li>
                  <li><Link href="/about-us/our-brands/giromex">Giromex</Link></li>
                  <li><Link href="/about-us/our-brands/le-goi">Le Goi</Link></li>
                  <li><Link href="/about-us/our-brands/sharemoney">Sharemoney</Link></li>
                  <li><Link href="/about-us/our-brands/uno">Uno</Link></li>
                  <li><Link href="/about-us/use-cases">Use Cases</Link></li>
                </ul>
              </div>
            </li>
            <li>
              <Link href="/our-solutions">Our Solutions</Link>
            </li>
            <li>
              <Link href="/careers">Careers</Link>
            </li>
            <li>
              <div className="dropdown">
                <button className="dropbtn">Regulatory</button>
                <ul className="dropdown-content">
                  <li><Link href="/regulatory/file-a-complaint">File a Complaint</Link></li>
                  <li><Link href="/regulatory/privacy-policy">Privacy Policy</Link></li>
                  <li><Link href="/regulatory/state-licenses">State Licenses</Link></li>
                </ul>
              </div>
            </li>
          </ul>
        </nav>
      </header>
      <main>
        {children}
      </main>
      <footer>
        [footer content]
      </footer>
    </>
  );
}