import { Inter } from 'next/font/google'
import '@/globals.css'
import MainLayout from '@/MainLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <MainLayout showLinkBar={true}>
      {children}
    </MainLayout>
  )
}
